### ISSUE TITLE
Installing from git fails

### ISSUE THREAD

**Issue by marcomilanesio** [gagneurlab/drop#620]
Hi,

```
$ conda create -c conda-forge -c bioconda -n snakemake snakemake
$ conda activate snakemake
(snakemake) $ pip install git+https://github.com/gagneurlab/drop.git@dev
(snakemake) $ mkdir drop_demo
(snakemake) $ drop demo
```

Results in:

```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/bin/drop", line 5, in <module>
    from drop.cli import main
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.12/site-packages/drop/__init__.py", line 1, in <module>
    from .setupDrop import *
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.12/site-packages/drop/setupDrop.py", line 2, in <module>
    from drop.config.DropConfig import DropConfig
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.12/site-packages/drop/config/__init__.py", line 1, in <module>
    from .DropConfig import DropConfig
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.12/site-packages/drop/config/DropConfig.py", line 1, in <module>
    from .SampleAnnotation import SampleAnnotation
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.12/site-packages/drop/config/SampleAnnotation.py", line 1, in <module>
    from drop import utils
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.12/site-packages/drop/utils.py", line 3, in <module>
    import wbuild
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.12/site-packages/wbuild/__init__.py", line 10, in <module>
    from . import autolink
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.12/site-packages/wbuild/autolink.py", line 6, in <module>
    from wbuild.utils import Config
  File "/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.12/site-packages/wbuild/utils.py", line 12, in <module>
    from snakemake import get_argument_parser, parse_config, SNAKEFILE_CHOICES
ImportError: cannot import name 'get_argument_parser' from 'snakemake' (/opt/homebrew/Caskroom/miniforge/base/envs/snakemake/lib/python3.12/site-packages/snakemake/__init__.py)

```

Thank you very much

**Comment by AtaJadidAhari** [comment]
Hi, this is an issue regarding snakemake. DROP doesn't work with snakemake >= 8.0. We enforce this in conda installation. If you want to install DROP via pip, you can downgrade snakemake yourself. `pip install snakemake==7.32` should do the trick.
